brew tap "homebrew/cask"
brew tap "homebrew/cask-drivers"
brew tap "homebrew/cask-fonts"
brew tap "homebrew/cask-versions"

brew cask install "google-chrome"
brew cask install "macdown"
brew cask install "postman"
brew cask install "slack"
brew cask install "spotify"
brew cask install "virtualbox"
brew cask install "visual-studio-code"
brew cask install "vlc"

# Quick Look Plugins (https://github.com/sindresorhus/quick-look-plugins)
brew cask install "qlcolorcode"
brew cask install "qlimagesize"
brew cask install "qlmarkdown"
brew cask install "qlstephen"
brew cask install "qlvideo"
brew cask install "quicklook-json"
brew cask install "suspicious-package"
brew cask install "webpquicklook"
